apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend  # Replace "backend" with your desired namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/inclassactivity-424815/backend:latest  # Replace this with your Docker image name
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "34.30.91.14"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "root"
